### ISSUE TITLE
Some questions about your modified code

### ISSUE THREAD

**Issue by tanveer6715** [Holmes2002/STEGO#1]
Hi thanks for your great work. I have some question about your codes:
1. Which trained model from the original STEGO you have fine tune for your dataset?
2. Have you used semisupervised approach for fine tuning as you have said in the docs that you have trained on 70 K images some wore labelled and some image were unlabelled?
3. I did not see any linear.py file in your codes.
4. What is the purpose of distilled model file?
 Thank you

**Comment by Holmes2002** [comment]
Well, I will answer your questions:
1. The model is trained in unsupervised origianal task, will be used for finetuning for supervised task
2.  Not semi, the model fistly tranied in unsupervised then finetune in supervised task
3. It is in collab file
4. My original purpose is that try to distill model to smaller model such as resnet 34 or 50 but After all I think This model is not too good. I think you should use availble model such as SAM of Facebook. It is better
